service: serverless-mnist
 
provider:
  name: aws #cloud provider
  region: ap-northeast-1 #region (mumbai)
  memorySize: 5124 #memory usage
  timeout: 300

functions:
  cifar:
    image: 027175241301.dkr.ecr.ap-northeast-1.amazonaws.com/cifar-serverless-v1:latest
    events:
      - http:
          path: inference 
          method: post 
          cors: true