org: akshatthakar
app: serverless-cifar
service: serverless-cifar
 
provider:
  name: aws #cloud provider
  region: ap-northeast-1 
  memorySize: 3000
  timeout: 300

functions:
  cifar:
    image: 027175241301.dkr.ecr.ap-northeast-1.amazonaws.com/cifar-serverless-v1:latest
    events:
      - http:
          path: inference 
          method: post 
          cors: true